-- Every column behind a Java primitive has to be NOT NULL.
--
-- Hibernate cannot read a NULL back into an int, long, double or boolean - it throws
-- PropertyAccessException. A list query maps a whole page at once, so ONE such row fails the entire
-- page: the screen shows nothing at all rather than one broken record. Writing is never affected,
-- because a primitive always has a value. The symptom is therefore always the same and always
-- misleading - records save fine and then do not appear.
--
-- That is what broke the dispatch list (see V15). secondary_pack_count was added to a populated
-- dispatch_items table; auto-DDL adds a column to a populated table without NOT NULL and without a
-- default, so every row already on file got a NULL, and the list had been failing ever since for
-- anything created before that change.
--
-- Auditing the generated schema showed 141 of the 334 primitive-backed columns are created nullable,
-- so every one of them is the same defect waiting for its column to be added a release late.
--
-- Only columns that are ACTUALLY nullable right now are touched: backfill the nulls with the
-- entity's own default, set that default, then restore NOT NULL. Anything already NOT NULL, or not
-- present in this database, is left alone. Safe to re-run, and safe to run before the tables exist.
--
-- Each column is repaired inside its own block. Across 300-odd columns something unforeseen - a
-- view depending on a column, a check constraint - should cost that one column, not fail the
-- migration and leave the application unable to start.

DO $$
DECLARE
    t   text;
    c   text;
    d   text;
    n   int := 0;
    cols text[][] := ARRAY[
        ['account_defaults','active','true'],
        ['account_groups','active','true'],
        ['account_groups','effects_gross_profit','false'],
        ['account_groups','is_primary','true'],
        ['account_groups','sub_account','false'],
        ['account_heads','active','true'],
        ['accounting_configs','active','true'],
        ['accounting_periods','period_month','0'],
        ['accounting_periods','period_year','0'],
        ['accounts','active','true'],
        ['accounts','is_bank','false'],
        ['accounts','is_central','false'],
        ['accounts','is_contra','false'],
        ['accounts','is_system','false'],
        ['accounts','overdraft','false'],
        ['accounts','show_opening_balance','false'],
        ['accounts','sub_account','false'],
        ['admin_locations','active','true'],
        ['agri_crop_data','sample_at_intake','false'],
        ['agri_crop_data','sample_at_sales_return','false'],
        ['agri_crop_data','sample_at_seed_expire','false'],
        ['agri_crop_data','sample_at_third_party','false'],
        ['agri_farmers','active','true'],
        ['agri_farmers','is_organizer','false'],
        ['agri_farmers','is_shareholder','false'],
        ['agri_packaging_designs','active','true'],
        ['agri_packaging_materials','active','true'],
        ['agri_packaging_materials','hybrid','false'],
        ['agri_process_boms','active','true'],
        ['agri_processing_screens','active','true'],
        ['agri_production_areas','active','true'],
        ['agri_variety_releases','active','true'],
        ['application_paths','active','true'],
        ['approval_instances','current_level','1'],
        ['approval_instances','max_level','0'],
        ['approval_rules','active','true'],
        ['approval_rules','approval_level','0'],
        ['approval_rules','sla_days','3'],
        ['approval_steps','level','0'],
        ['asset_groups','active','true'],
        ['asset_groups','useful_life_years','5'],
        ['asset_purchase_definitions','active','true'],
        ['auto_post_vouchers','active','true'],
        ['bag_sizes','active','true'],
        ['balance_sheet_config','active','true'],
        ['balance_sheet_config','display_order','0'],
        ['balance_sheet_config','show_sub_total','true'],
        ['bank_accounts','active','true'],
        ['bank_statements','matched','false'],
        ['bank_vouchers','is_ac_payee','false'],
        ['bank_vouchers','is_rtgs','false'],
        ['bank_vouchers','multi_cheque','false'],
        ['bank_vouchers','single_cheque_print','false'],
        ['bill_of_materials','active','true'],
        ['branches','active','true'],
        ['branches','is_head_office','false'],
        ['brands','active','true'],
        ['budget_entries','period_month','0'],
        ['budget_entries','period_year','0'],
        ['byproduct_types','active','true'],
        ['companies','active','true'],
        ['contacts','is_primary','false'],
        ['contract_items','lead_time_days','0'],
        ['cost_centers','active','true'],
        ['crop_variety_tests','active','true'],
        ['crop_variety_tests','defined','false'],
        ['crop_variety_tests','is_mandatory','false'],
        ['crop_variety_tests','update_inventory','false'],
        ['currencies','active','true'],
        ['currencies','decimal_places','2'],
        ['currencies','is_base_currency','false'],
        ['customer_discounts','active','true'],
        ['customer_pricing','active','true'],
        ['customers','active','true'],
        ['dealer_regions','active','true'],
        ['dealers','active','true'],
        ['demand_forecasts','confidence_level','0'],
        ['demand_forecasts','forecast_year','0'],
        ['departments','active','true'],
        ['depreciation_entries','period_month','0'],
        ['depreciation_entries','period_year','0'],
        ['depreciation_entries','posted','false'],
        ['designations','active','true'],
        ['dimension_values','active','true'],
        ['dimensions','active','true'],
        ['dimensions','mandatory','false'],
        ['discount_definitions','active','true'],
        ['discount_schemes','active','true'],
        ['dispatch_items','package_count','1'],
        ['dispatch_items','secondary_pack_count','0'],
        ['dispatches','total_packages','0'],
        ['early_payment_discounts','applied','false'],
        ['employee_benefits','active','true'],
        ['employee_benefits','is_percentage','false'],
        ['employee_benefits','taxable','false'],
        ['employee_pay_details','is_loss_of_pay_applicable','false'],
        ['employee_pay_details','is_over_time_applicable','false'],
        ['employee_statuses','active','true'],
        ['exchange_rates','active','true'],
        ['feature_privileges','granted','true'],
        ['field_inspection_rounds','recommend_rejection','false'],
        ['field_inspection_rounds','round_number','0'],
        ['field_plots','active','true'],
        ['field_producers','active','true'],
        ['field_producers','is_organizer','false'],
        ['field_producers','is_shareholder','false'],
        ['fixed_assets','active','true'],
        ['fixed_assets','useful_life_years','5'],
        ['geo_cities','active','true'],
        ['geo_countries','active','true'],
        ['geo_districts','active','true'],
        ['geo_mandals','active','true'],
        ['geo_states','active','true'],
        ['godowns','active','true'],
        ['godowns','cold_storage','false'],
        ['godowns','machine_availability','false'],
        ['godowns','packing_material_storage','false'],
        ['holidays','active','true'],
        ['holidays','year','0'],
        ['hr_wfh_requests','days','0'],
        ['inventory_app_features','enabled','true'],
        ['inventory_issues','truck_involved','false'],
        ['inventory_locations','active','true'],
        ['invoices','posted','false'],
        ['iot_devices','active','true'],
        ['leave_applications','days','0'],
        ['leave_types','active','true'],
        ['leave_types','carry_forward','false'],
        ['leave_types','days_allowed','0'],
        ['leave_types','paid','true'],
        ['ledger_opening_balances','sub_account','false'],
        ['ledger_opening_balances','visible','true'],
        ['location_stock_transfers','posted','false'],
        ['login_tracking','force_logged_off','false'],
        ['lot_series','active','true'],
        ['manufacturing_app_features','enabled','true'],
        ['material_groups','active','true'],
        ['material_groups','batch_wise_receipt','false'],
        ['material_groups','has_expiry_period','false'],
        ['material_groups','sellable','false'],
        ['material_items','active','true'],
        ['material_items','batch_wise_receipt','false'],
        ['material_items','has_expiry_period','false'],
        ['material_items','sellable','false'],
        ['migration_batches','error_records','0'],
        ['migration_batches','processed_records','0'],
        ['migration_batches','total_records','0'],
        ['mst_pricing_methods','active','true'],
        ['net_sales_closings','closed','true'],
        ['nets','active','true'],
        ['nurseries','active','true'],
        ['operation_types','active','true'],
        ['organizers','active','true'],
        ['organizers','is_supplier','false'],
        ['packaging_bags','active','true'],
        ['packing_materials','active','true'],
        ['packing_types','active','true'],
        ['pay_cycles','active','true'],
        ['pay_grades','active','true'],
        ['pay_grades','is_loss_of_pay_applicable','false'],
        ['pay_grades','is_over_time_applicable','false'],
        ['payment_methods','active','true'],
        ['payment_methods','bank_required','false'],
        ['payment_methods','reference_required','false'],
        ['payment_terms','active','true'],
        ['payment_terms','discount_days','0'],
        ['payment_terms','due_days','30'],
        ['payment_terms','has_early_payment_discount','false'],
        ['payment_terms','penalty_after_days','0'],
        ['payslips','leave_days','0'],
        ['payslips','pay_month','0'],
        ['payslips','pay_year','0'],
        ['payslips','present_days','0'],
        ['payslips','working_days','0'],
        ['period_closes','period_month','0'],
        ['period_closes','period_year','0'],
        ['plant_categories','active','true'],
        ['plant_families','active','true'],
        ['plant_process_sequences','active','true'],
        ['plant_process_sequences','sequence_order','0'],
        ['plant_variants','active','true'],
        ['plant_variants','hybrid','false'],
        ['plant_variants','product_wise_sales_plan','false'],
        ['plant_variants','transgenic','false'],
        ['possible_deductions','active','true'],
        ['possible_deductions','is_cost_deduction','false'],
        ['possible_deductions','is_per_bag','false'],
        ['possible_deductions','is_weight_deduction','false'],
        ['price_lists','active','true'],
        ['price_lists','is_default','false'],
        ['pricing_methods','active','true'],
        ['pricing_methods','advance_from_grower','false'],
        ['pricing_methods','revenue_stamp','false'],
        ['pricing_methods','sealing_charges','false'],
        ['pricing_schemes','active','true'],
        ['process_boms','active','true'],
        ['process_issue_configs','is_enabled','true'],
        ['process_job_input_lots','complete','false'],
        ['process_loss_items','selected','true'],
        ['process_steps','active','true'],
        ['process_steps','allow_multiple_inputs','false'],
        ['process_steps','has_byproduct','false'],
        ['process_steps','has_process_loss','false'],
        ['process_steps','has_waste','false'],
        ['process_steps','quality_check_required','false'],
        ['process_template_steps','is_optional','false'],
        ['process_template_steps','sequence_number','0'],
        ['process_templates','active','true'],
        ['process_treatments','active','true'],
        ['processing_lines','active','true'],
        ['processing_screens','active','true'],
        ['processing_sequences','active','true'],
        ['product_bom_lines','sort_order','0'],
        ['product_categories','active','true'],
        ['product_lines','active','true'],
        ['product_skus','active','true'],
        ['product_skus','use_sticker','false'],
        ['product_specifications','display_order','0'],
        ['product_specifications','is_mandatory','false'],
        ['production_app_features','enabled','false'],
        ['production_intakes','is_direct_return','false'],
        ['production_intakes','is_free_sample_return','false'],
        ['production_job_allocations','initiated','false'],
        ['production_jobs','only_quality_tested','false'],
        ['production_plan_items','priority_order','0'],
        ['products','active','true'],
        ['products','track_inventory','true'],
        ['promotions','active','true'],
        ['promotions','buy_quantity','0'],
        ['promotions','get_quantity','0'],
        ['promotions','stackable','false'],
        ['promotions','usage_count','0'],
        ['promotions','usage_limit','0'],
        ['purchase_app_features','enabled','true'],
        ['purchase_invoices','tds_applicable','false'],
        ['purchase_quotation_items','delivery_days','0'],
        ['purchase_quotations','delivery_days','0'],
        ['purchase_work_orders','active','true'],
        ['report_definitions','active','true'],
        ['report_definitions','default_page_size','20'],
        ['report_definitions','is_public','false'],
        ['report_definitions','run_count','0'],
        ['report_runs','duration_ms','0'],
        ['report_runs','record_count','0'],
        ['report_schedules','active','true'],
        ['report_schedules','hour','8'],
        ['role_hierarchy','level_order','99'],
        ['role_ranges','active','true'],
        ['roles','is_system','false'],
        ['salary_components','active','true'],
        ['salary_components','is_percentage','false'],
        ['salary_components','taxable','true'],
        ['salary_components','value','0'],
        ['salary_elements','active','true'],
        ['salary_elements','taxable','false'],
        ['sales_area_levels','active','true'],
        ['sales_configs','active','true'],
        ['sales_customer_stock_transfers','freight_paid','false'],
        ['sales_customer_stock_transfers','posted','false'],
        ['sales_plans','plan_year','0'],
        ['sales_representatives','active','true'],
        ['sales_schemes','active','true'],
        ['sales_territories','active','true'],
        ['sales_territories','is_export','false'],
        ['season_periods','active','true'],
        ['seasons','is_active','true'],
        ['seed_categories','active','true'],
        ['seed_classes','active','true'],
        ['seed_production_stages','active','true'],
        ['seed_production_stages','stage_order','0'],
        ['seed_states','active','true'],
        ['server_configs','active','true'],
        ['service_categories','active','true'],
        ['service_definitions','active','true'],
        ['service_definitions','work_order','false'],
        ['share_capital','active','true'],
        ['shareholders','active','true'],
        ['statutory_deductions','active','true'],
        ['stock_closings','total_bags','0'],
        ['stock_closings','total_issues','0'],
        ['stock_closings','total_lots','0'],
        ['stock_closings','total_receipts','0'],
        ['storage_locations','active','true'],
        ['storage_locations','is_default','false'],
        ['sub_accounts','active','true'],
        ['supplier_contracts','auto_renew','false'],
        ['supplier_contracts','notice_period_days','30'],
        ['supplier_contracts','renewal_term_months','12'],
        ['supplier_performance','accepted_lots','0'],
        ['supplier_performance','late_orders','0'],
        ['supplier_performance','on_time_orders','0'],
        ['supplier_performance','rejected_lots','0'],
        ['supplier_performance','total_orders','0'],
        ['tax_rates','active','true'],
        ['tax_rates','is_compound','false'],
        ['tds_categories','active','true'],
        ['test_definitions','active','true'],
        ['test_definitions','no_of_replications','0'],
        ['test_locations','active','true'],
        ['test_parameters','display','true'],
        ['test_parameters','display_order','0'],
        ['test_parameters','is_mandatory','true'],
        ['test_parameters','key_param','false'],
        ['test_parameters','result_affects','false'],
        ['treatments','active','true'],
        ['units_of_measure','active','true'],
        ['units_of_measure','base_unit','false'],
        ['units_of_measure','decimal_places','2'],
        ['uom_categories','active','true'],
        ['uom_conversions','active','true'],
        ['uom_conversions','bidirectional','true'],
        ['users','change_password_on_login','false'],
        ['users','email_verified','false'],
        ['users','failed_login_attempts','0'],
        ['vat_definitions','active','true'],
        ['vendor_qualifications','compliance_score','0'],
        ['vendor_qualifications','financial_score','0'],
        ['vendor_qualifications','overall_score','0'],
        ['vendor_qualifications','technical_score','0'],
        ['vendors','active','true'],
        ['villages','active','true'],
        ['voucher_books','active','true'],
        ['warehouses','active','true'],
        ['warehouses','is_default','false'],
        ['waste_types','active','true'],
        ['work_centers','active','true'],
        ['workflow_approvals','step_order','0'],
        ['workflow_definitions','active','true'],
        ['workflow_instances','current_step','1'],
        ['workflow_steps','step_order','0'],
        ['workflow_steps','timeout_days','3'],
        ['working_days','active','true'],
        ['working_days','break_minutes','60'],
        ['working_days','is_working','true']
    ];
    i int;
BEGIN
    FOR i IN 1 .. array_length(cols, 1) LOOP
        t := cols[i][1];
        c := cols[i][2];
        d := cols[i][3];

        IF EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = t AND column_name = c AND is_nullable = 'YES')
        THEN
            BEGIN
                EXECUTE format('UPDATE %I SET %I = %s WHERE %I IS NULL', t, c, d, c);
                EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET DEFAULT %s', t, c, d);
                EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET NOT NULL', t, c);
                n := n + 1;
            EXCEPTION WHEN OTHERS THEN
                RAISE NOTICE 'Skipped %.%: %', t, c, SQLERRM;
            END;
        END IF;
    END LOOP;

    RAISE NOTICE 'Primitive-backed columns made NOT NULL: %', n;
END $$;
